# Generated by Django 5.1 on 2026-02-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('correo', models.EmailField(max_length=75)),
                ('telefono', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('codigo_qr', models.ImageField(blank=True, help_text='ESTE CODIGO SE GENERARA AUTOMATICAMENTE y para descargarlo presione el click derecho del mouse sobre el enlace con la ruta, luego "guargar como", y a continuacion seleccione la carpeta de destino (solo si posee los permisos)', max_length=50, null=True, upload_to='qr/', verbose_name='Codigo Qr')),
                ('materias', models.ManyToManyField(to='asistencia.materias')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.personas', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesores',
                'permissions': (('descargar_qr', 'Descargar los codigos qr'),),
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(auto_now=True)),
                ('salida', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.profesores')),
            ],
            options={
                'verbose_name_plural': 'Asistencia',
                'db_table': 'asistencia',
            },
        ),
    ]
